spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/associationMapping
    username: root
    password: saiShyam1$
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true